export const UPDATE_DATA = 'UPDATE_DATA';
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const UPDATE_DISPLAY_LENGTH = 'UPDATE_DISPLAY_LENGTH';
export const IS_LOADING = 'IS_LOADING';
export const IS_NOT_LOADING = 'IS_NOT_LOADING';
