export enum TimeRange {
  SHORT_TERM = "short_term",
  MEDIUM_TERM = "medium_term",
  LONG_TERM = "long_term",
}

export const SPOTIFY_CONTEXT = "SPOTIFY_CONTEXT";

export enum CacheKey {
  FOLLOWED_ARTISTS_COUNT = "FOLLOWED_ARTISTS_COUNT",
  ALBUMS_SAVED_COUNT = "ALBUMS_SAVED_COUNT",
  TRACKS_FAVORITED_COUNT = "TRACKS_FAVORITED_COUNT",
  DASHBOARD_TOP_ARTISTS = "DASHBOARD_TOP_ARTISTS",
  DASHBOARD_TOP_ALBUMS = "DASHBOARD_TOP_ALBUMS",
  DASHBOARD_TOP_TRACKS = "DASHBOARD_TOP_TRACKS",
  ARTIST_COUNTRIES_DATA = "ARTIST_COUNTRIES_DATA",
  UNKNOWN_ARTISTS = "UNKNOWN_ARTISTS",
}

export enum ApiMethod {
  GET = "GET",
  POST = "POST",
  PUT = "PUT",
  PATCH = "PATCH",
  DELETE = "DELETE",
}

export const AUDIODB_BASE_URL = `https://www.theaudiodb.com/api/v1/json/${
  import.meta.env.VITE_AUDIODB_KEY
}`;
