export enum TimeRange {
  SHORT_TERM = 'short_term',
  MEDIUM_TERM = 'medium_term',
  LONG_TERM = 'long_term',
}

export const SPOTIFY_CONTEXT = 'SPOTIFY_CONTEXT';

export enum CacheKey {
  FOLLOWED_ARTISTS_COUNT = 'FOLLOWED_ARTISTS_COUNT',
  ALBUMS_SAVED_COUNT = 'ALBUMS_SAVED_COUNT',
  TRACKS_FAVORITED_COUNT = 'TRACKS_FAVORITED_COUNT',
  DASHBOARD_TOP_ARTISTS = 'DASHBOARD_TOP_ARTISTS',
  DASHBOARD_TOP_ALBUMS = 'DASHBOARD_TOP_ALBUMS',
  DASHBOARD_TOP_TRACKS = 'DASHBOARD_TOP_TRACKS',
}
