export const SPOTIFY_CONTEXT = 'SPOTIFY_CONTEXT';

export enum CacheKey {
  FOLLOWED_ARTISTS_COUNT = 'FOLLOWED_ARTISTS_COUNT',
  ALBUMS_SAVED_COUNT = 'ALBUMS_SAVED_COUNT',
  TRACKS_FAVORITED_COUNT = 'TRACKS_FAVORITED_COUNT',
}
